QT_XMLPATTERNS_VERSION = $$QT_VERSION
QT_XMLPATTERNS_MAJOR_VERSION = $$QT_MAJOR_VERSION
QT_XMLPATTERNS_MINOR_VERSION = $$QT_MINOR_VERSION
QT_XMLPATTERNS_PATCH_VERSION = $$QT_PATCH_VERSION

QT.xmlpatterns.name = QtXmlPatterns
QT.xmlpatterns.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtXmlPatterns
QT.xmlpatterns.libs = $$QT_MODULE_LIB_BASE
QT.xmlpatterns.depends = core network

QT_CONFIG += xmlpatterns
